### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'FirebaseCppApp-11_1_0': The specified module could not be found.

### ISSUE THREAD

**Issue by mic89** [firebase-unity/firebase-crashlytics#1]
Package with Unity IL2CPP for android, then bootup the game, firebase crashlytics thow 'DllNotFoundException'.

Version 11.1.0

DllNotFoundException: Unable to load DLL 'FirebaseCppApp-11_1_0': The specified module could not be found.
06-08 10:25:51.361 31513 31654 E Unity   :   at Firebase.AppUtilPINVOKE.FirebaseApp_DefaultName_get () [0x00000] in <00000000000000000000000000000000>:0
06-08 10:25:51.361 31513 31654 E Unity   :   at Firebase.FirebaseApp.get_DefaultName () [0x00000] in <00000000000000000000000000000000>:0
06-08 10:25:51.361 31513 31654 E Unity   :   at Firebase.FirebaseApp.get_DefaultInstance () [0x00000] in <00000000000000000000000000000000>:0
06-08 10:25:51.361 31513 31654 E Unity   :   at Firebase.Crashlytics.AndroidImpl..ctor () [0x00000] in <00000000000000000000000000000000>:0
06-08 10:25:51.361 31513 31654 E Unity   :   at Firebase.Crashlytics.Impl.Make () [0x00000] in <00000000000000000000000000000000>:0
06-08 10:25:51.361 31513 31654 E Unity   :   at Firebase.Crashlytics.Crashlytics+PlatformAccessor..cctor () [0x00000] in <00000000000000000000000000000000>:0
06-08 10:25:51.361 31513 31654 E Unity   :   at Firebase.Crashlytics.Crashlytics.Log (System.String message) [0x00000] in <00000000000000000000000000000000>:0
06-08 10:25:51.361 31513 31654 E Unity   :   at LogManager+<>c.<Init>b__0_0 (System.String nContent, System.String nStackTrace, UnityEngine.LogType nType) [0x00000] in <00000000000000000000000000000000>:0
06-08 10:25:51.361 31513 31654 E Unity   :   at UnityEngine.Applicat

**Comment by yenmoc** [comment]
Hello!, `DllNotFoundException: Unable to load DLL 'FirebaseCppApp-11_1_0`
is the error specified that FirebaseCppApp was not included in the build correctly

**Comment by yenmoc** [comment]
To fix this error you can try the following steps
1, Delete the Assets/GeneratedLocalRepo folder in unity
2, Delete the firebase app in the Assets/Plugins/Android folder
3, Delete the file google-services.json
4, Import the google-services.json file again
5, Force Resolve through the menu Assets/External Dependency Manager/Android Resolver/Force Resolve
6, Build again


make sure the Assets/GeneratedLocalRepo folder is created
